### ISSUE TITLE
Bug in platHttpServerTask

### ISSUE THREAD

**Issue by jhinklejr** [Spritetm/esphttpd-freertos#1]
Function: static void platHttpServerTask(void *pvParameters) 

code starting at line 192 ... I expanded it with spaces so you can see the bug

				if (FD_ISSET(rconn[x].fd, &readset))
                                 {
					precvbuf=(char*)malloc(RECV_BUF_SIZE);
					if (precvbuf==NULL)
                                                                  httpd_printf("platHttpServerTask: memory exhausted!\n");

BUG--> if malloc fails you still fall into rcv which will crash .... 

					ret=recv(rconn[x].fd, precvbuf, RECV_BUF_SIZE,0);
					if (ret > 0) {
						//Data received. Pass to httpd.
						httpdRecvCb(&rconn[x], rconn[x].ip, rconn[x].port, precvbuf, ret);
					} else {
						//recv error,connection close
						httpdDisconCb(&rconn[x], rconn[x].ip, rconn[x].port);
						close(rconn[x].fd);
						rconn[x].fd=-1;
					}
					if (precvbuf) free(precvbuf);
				}

I'm not sure the best solution ... I was going to say 

                                if (precvbuf==NULL)
                                {
                                     httpd_printf("platHttpServerTask: memory exhausted!\n");
                                     continue;
                                 }

but that would just lead to an un-blocked select and the task would spin.

I will probably process as if rcv failed - close socket and disconnect.

Please let me know what your thoughts are.

Joe

**Comment by jhinklejr** [comment]
Just a comment ... I know the ESP has quit a bit of ram ....

I did a search for malloc in the file httpd-FreeRtos.c and there are a number of malloc calls that will crash if no memory is available because the return from malloc is not checked and proper action taken.

If I'm being too picky - I apologize.

Joe

**Comment by jhinklejr** [comment]
After all that is said and done -- I think you have provided a great lib.

I am going thru your code line by line to understand it.  I can't use it if I don't understand it.

Again - great work -- Thanks.

Joe

**Comment by jhinklejr** [comment]
Sorry - I didn't understand the CLOSE button.

**Comment by Spritetm** [comment]
In general, behaviour when malloc fails isn't the best possible - I should take a look at that but am fairly busy at the moment. I'll see if I can fix it when I have the time, if you (or anyone else) feel like fixing it before that, I'd love to see patches or pull requests.

**Comment by Spritetm** [comment]
Got some time to fix it. The results still aren't 100% what I would like to see (aborted transfers etc) but if anything the webserver isn't crashing.
